### ISSUE TITLE
Include APIError class into field __all__

### ISSUE THREAD

**Issue by alex2304** [qweeze/wex-api-client#1]
Hi! I'm using your client and I've noticed that you are rising exceptions of type `wex.APIError`. But the type of the exception you rise is not available for outers, so it's not possible to handle exactly that type of exception.

Please, include it into your __all__ attribute to make it available to outer world. Thank you!
![image](https://user-images.githubusercontent.com/7988418/42094780-8492653c-7bb9-11e8-9d6b-57c663af8b51.png)

**Comment by qweeze** [comment]
Sure, fixed in 0.1.7 (b85b3a9ff6bd1e53e8893a8220c492c1e0dc541f)
Thanks!

**Comment by alex2304** [comment]
thank you!
